# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import audio_test_pb2 as audio__test__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DutAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/audiotest.DutAgent/Health',
                request_serializer=audio__test__pb2.HealthRequest.SerializeToString,
                response_deserializer=audio__test__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PrepareRecording = channel.unary_unary(
                '/audiotest.DutAgent/PrepareRecording',
                request_serializer=audio__test__pb2.PrepareRecordingRequest.SerializeToString,
                response_deserializer=audio__test__pb2.PrepareRecordingResponse.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/audiotest.DutAgent/StartRecording',
                request_serializer=audio__test__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=audio__test__pb2.StartRecordingResponse.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/audiotest.DutAgent/StopRecording',
                request_serializer=audio__test__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=audio__test__pb2.StopRecordingResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/audiotest.DutAgent/DownloadFile',
                request_serializer=audio__test__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=audio__test__pb2.FileChunk.FromString,
                _registered_method=True)


class DutAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Server-streaming: agent sends file chunks back to Control PC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DutAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=audio__test__pb2.HealthRequest.FromString,
                    response_serializer=audio__test__pb2.HealthResponse.SerializeToString,
            ),
            'PrepareRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareRecording,
                    request_deserializer=audio__test__pb2.PrepareRecordingRequest.FromString,
                    response_serializer=audio__test__pb2.PrepareRecordingResponse.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=audio__test__pb2.StartRecordingRequest.FromString,
                    response_serializer=audio__test__pb2.StartRecordingResponse.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=audio__test__pb2.StopRecordingRequest.FromString,
                    response_serializer=audio__test__pb2.StopRecordingResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=audio__test__pb2.DownloadFileRequest.FromString,
                    response_serializer=audio__test__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audiotest.DutAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audiotest.DutAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DutAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiotest.DutAgent/Health',
            audio__test__pb2.HealthRequest.SerializeToString,
            audio__test__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiotest.DutAgent/PrepareRecording',
            audio__test__pb2.PrepareRecordingRequest.SerializeToString,
            audio__test__pb2.PrepareRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiotest.DutAgent/StartRecording',
            audio__test__pb2.StartRecordingRequest.SerializeToString,
            audio__test__pb2.StartRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiotest.DutAgent/StopRecording',
            audio__test__pb2.StopRecordingRequest.SerializeToString,
            audio__test__pb2.StopRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/audiotest.DutAgent/DownloadFile',
            audio__test__pb2.DownloadFileRequest.SerializeToString,
            audio__test__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
